version: '2'

services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-networks

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '5000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge

volumes:
  dbdata:
    driver: local
