version: '2'

services:
  db: 
    image: mysql:latest
    container_name: db
    volumes: 
      - dbdata:/var/lib/mysql/
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: Simple
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - 'app-networks'

networks:
  app-networks:
    driver: bridge

volumes:
  dbdata:
    driver: local